### ISSUE TITLE
Enhancement: Contributing guidelines

### ISSUE THREAD

**Issue by milancurcic** [cdslaborg/paramonte#12]
Have contributing guidelines, ideally in a CONTRIBUTING.md file. 

https://github.com/openjournals/joss-reviews/issues/2741

**Comment by shahmoradi** [comment]
Thanks, Milan, The contribution guidelines are already provided in [the documentation](https://www.cdslab.org/paramonte/notes/contributing/development/general/). For the sake of completeness, however, I have now added the guidelines to the GitHub repository as well: [CONTRIBUTING.md](https://github.com/cdslaborg/paramonte/blob/main/CONTRIBUTING.md), and [CONTRIBUTIN-KERNELG.md](https://github.com/cdslaborg/paramonte/blob/main/CONTRIBUTING-KERNEL.md)

**Comment by milancurcic** [comment]
Ah, you're right, I misses that, all good.
