### ISSUE TITLE
0649417617​

### ISSUE THREAD

**Issue by Higggg** [cdslaborg/paramonte#2]
วันที่/เวลา	ปลายทาง	หน่วย	ค่าบริการ (฿)
บริการรับส่งข้อความ MMS (ครั้ง)	1	6.42
28/10/2563 12:05:00	0858899541	1	6.42
Internet	16 GB 124 MB 503 KB	2.75
03/10/2563 01:39:01	Mobilenet	174 KB	0.00
03/10/2563 02:55:24	Mobilenet	13 MB 129 KB	0.00
03/10/2563 05:55:25	Mobilenet	128 KB	0.00
03/10/2563 07:47:36	Mobilenet	245 KB	0.00
03/10/2563 07:47:44	Mobilenet	7 MB 420 KB	0.00
03/10/2563 08:09:12	Mobilenet	8 MB 231 KB	0.00
03/10/2563 08:16:02	Mobilenet	1 MB 288 KB	0.00
03/10/2563 08:18:20	Mobilenet	1 MB 309 KB	0.00
03/10/2563 11:15:50	Mobilenet	692 KB	0.00
03/10/2563 14:37:59	Mobilenet	6 MB 869 KB	0.00
03/10/2563 17:18:04	Mobilenet	33 MB 507 KB	0.00
03/10/2563 21:01:20	Mobilenet	1 MB 55 KB	0.00
03/10/2563 22:32:39	Mobilenet	752 KB	0.00
03/10/2563 22:33:57	Mobilenet	115 KB	0.00
03/10/2563 22:35:16	Mobilenet	66 MB 614 KB	0.00
03/10/2563 23:59:08	Mobilenet	16 KB	0.00
04/10/2563 00:00:00	Mobilenet	170 KB	0.00
- ของ 303 รายการ

1
2
3
4
5
...
16

20
ย้อนกลับ
มีข้อสงสัยเกี่ยวกับรายละเอียดการใช้บริการ กรุณาเลือกแจ้งปัญหา เพื่อแจ้งรายละเอียด
แจ้งปัญหา

**Comment by shahmoradi** [comment]
This issue appears to be spam. So I am going to close it.
