### ISSUE TITLE
Building from source fails on x86-64 Ubuntu 18.04

### ISSUE THREAD

**Issue by milancurcic** [cdslaborg/paramonte#3]
This is paramonte checked out from master at commit ebc402f4a0dfb1df4327e6bf92f04d870dffbdb1.

I attach the install output: [out.txt](https://github.com/cdslaborg/paramonte/files/5525028/out.txt)

**Comment by shahmoradi** [comment]
@milancurcic Thanks for pointing this out. This was apparently an issue with the way OpenCoarrays library creates its setup files, sometimes creating the file and sometimes not, depending on whether it finds a suitable MPI library at installation time. It should be now fixed. If it happens again, please let us know, perhaps along with the specific configuration with which you are building the library.
