### ISSUE TITLE
Broken link on installation page..

### ISSUE THREAD

**Issue by arwelHughes** [cdslaborg/paramonte#37]
I'm trying to get hold of Matlab Paramonte for Linux. When I go the the installation page....

https://www.cdslab.org/paramonte/notes/installation/matlab/

..and click on the link for linux, it tries to open:
https://github.com/cdslaborg/paramonte/releases/latest/download/libparamonte_matlab_linux_x64.tar.gz

This is a broken link, and I've failed to find the correct one. In fact, just going to paramonte/releases seems to have links for the source code, but I can't find up to date Linux binaries anywhere! Where do the pre-bui;t binaries live now??

**Comment by shahmoradi** [comment]
@arwelHughes Thanks for raising this issue. This happened when we created a new (final) release of the previous major version of the library a few days ago, but we did not update the documentation. The [page you mentioned now contained the corrected links](https://www.cdslab.org/paramonte/notes/installation/matlab/#the-fast-way), and the correct download link is: https://github.com/cdslaborg/paramonte/releases/download/v1.5.1/libparamonte_matlab_linux_x64.tar.gz

I mentioned to others here that the new MATLAB version will be out sometime this week. Unfortunately, I (and others) have many other daily work responsibilities that push the next major release further into the future. But the end is near, and there is light at the end of the tunnel. So please stay tuned and be patient for just a bit longer.

**Comment by shahmoradi** [comment]
@arwelHughes I am going to close this issue as a resolved case. Please reopen it to continue the discussion if that is not the case. Thanks.
